# Generated by Django 5.1.7 on 2025-03-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_category_event_sub_category'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajoins',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_media', to='events.event'),
        ),
    ]
