# Generated by Django 5.1.7 on 2025-03-24 12:23

import api.memberships.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nric_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=3)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('secondary_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('city_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('residential_status', models.CharField(blank=True, choices=[('sp', 's-pass'), ('ep', 'Employment Pass'), ('pr', 'Permanent Resident'), ('ctz', 'Citizen')], max_length=5, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to=api.memberships.models.profile_image_path)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('educational_qualifications', models.CharField(blank=True, max_length=200, null=True)),
                ('other_societies', models.CharField(blank=True, max_length=200, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('associate', 'Associate'), ('others', 'Others')], max_length=200, null=True)),
                ('membership_no', models.CharField(max_length=20)),
                ('secretary_approved_date', models.DateTimeField(blank=True, null=True)),
                ('president_approved_date', models.DateTimeField(blank=True, null=True)),
                ('registration_status', models.CharField(max_length=20)),
                ('membership_status', models.BooleanField(default=False)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('terminated_date', models.DateTimeField(blank=True, null=True)),
                ('inactive_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('inactive_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactive_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('president_admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_admin_user', to=settings.AUTH_USER_MODEL)),
                ('secretary_admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_admin_user', to=settings.AUTH_USER_MODEL)),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_by', to=settings.AUTH_USER_MODEL)),
                ('registered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_registered_user', to='memberships.registereduser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
