# Generated by Django 5.1.7 on 2025-04-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUsers.adminuserrole'),
        ),
    ]
