# Generated by Django 5.1.7 on 2025-04-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsers', '0002_adminuser_admin_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
