# Generated by Django 5.1.7 on 2025-04-09 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUsers', '0003_adminuserrole_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserrole',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
