# Generated by Django 5.1.7 on 2025-03-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcategory',
            options={'verbose_name_plural': 'Donation Categories'},
        ),
        migrations.AlterModelOptions(
            name='donationsubcategory',
            options={'verbose_name_plural': 'Donation Sub Categories'},
        ),
    ]
