# Generated by Django 5.1.7 on 2025-04-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberuser',
            name='subscrd_flag',
            field=models.CharField(blank=True, default='P', max_length=10, null=True),
        ),
    ]
