# Generated by Django 5.1.7 on 2025-03-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event Categories'},
        ),
        migrations.AlterModelOptions(
            name='eventsubcategory',
            options={'verbose_name_plural': 'Event Sub Categories'},
        ),
        migrations.AlterField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
