# Generated by Django 5.1.7 on 2025-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
