# Generated by Django 5.1.7 on 2025-05-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_category_event_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory'),
        ),
    ]
